name = "ses-email-demo-worker-dev"
main = "./src/index.ts"
compatibility_date = "2024-05-13"
workers_dev = false

[dev]
ip = "localhost"
local_protocol = "http"
port = 61023

[vars]
ENVIRONMENT = "dev"
AWS_SES_REGION = "us-east-2"

[version_metadata]
binding = "CF_VERSION_METADATA"


[env.production]
name = "ses-email-demo-worker"
minify = true
logpush = true

[env.production.vars]
ENVIRONMENT = "production"
AWS_SES_REGION = "us-east-2"

[env.production.triggers]
crons = [ "4 * * * *" ]

[env.production.version_metadata]
binding = "CF_VERSION_METADATA"
