name = "ses-email-demo-worker-dev"
main = "./src/index.ts"
compatibility_date = "2024-05-13"
workers_dev = false

[dev]
ip = "localhost"
local_protocol = "http"
port = 61023

[vars]
ENVIRONMENT = "dev"

[env.production]
name = "ses-email-demo-worker"
minify = true
logpush = true

[env.production.vars]
ENVIRONMENT = "production"

[env.production.triggers]
crons = [ "4 * * * *" ]
